# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('unread', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_messages', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('income_messages', models.IntegerField(default=0)),
                ('outcome_messages', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='messageroom',
            name='messages_list',
            field=models.ManyToManyField(to='user_messages.MessagesList'),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='participant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='message_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_messages.MessageRoom'),
        ),
        migrations.AddField(
            model_name='message',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
