# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_auto_20170328_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='room_preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
