# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_messageroom_room_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='room_preview',
        ),
    ]
