# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0008_auto_20170530_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='target_message_list',
            new_name='receiver_message_list',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='author_message_list',
            new_name='sender_message_list',
        ),
    ]
