# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0009_auto_20170607_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_list',
        ),
    ]
