# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0010_remove_message_message_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_message_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to='user_messages.MessageList'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_message_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='user_messages.MessageList'),
        ),
    ]
